### ISSUE TITLE
HAP-NodeJS Warning

### ISSUE THREAD

**Issue by agneevX** [merdok/homebridge-webos-tv#227]
Hi,

I'm getting this warning in HB logs:

```
[4/29/2020, 17:23:03] [webostv] webOS - init - initializing devices
[4/29/2020, 17:23:03] [webostv] webOS - init - initializing device with name: Old Room TV
HAP-NodeJS WARNING: The accessory 'Old Room TV' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
[4/29/2020, 17:23:03] [webostv] webOS - init - initializing device with name: New Room TV
HAP-NodeJS WARNING: The accessory 'New Room TV' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
```

**Comment by agneevX** [comment]
Maybe this can fix #223.

**Comment by merdok** [comment]
This is strange, i do not get the warning on my machine. What version of HAP-NodeJS do you have installed?

**Comment by coalfield** [comment]
@agneevX same issue here

> [4/29/2020, 8:32:07 PM] [webostv] webOS - init - initializing device with name: LG Television
> HAP-NodeJS WARNING: The accessory 'LG Television' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!

**Comment by merdok** [comment]
Can you please post your HAP-NodeJS version?

**Comment by coalfield** [comment]
Sorry I am not sure how to find it out?

**Comment by merdok** [comment]
How about your homebridge version?

**Comment by agneevX** [comment]
> How about your homebridge version?

Its 1.0.3.

**Comment by coalfield** [comment]
> How about your homebridge version?

1.0.3 too

**Comment by agneevX** [comment]
> This is strange, i do not get the warning on my machine. What version of HAP-NodeJS do you have installed?

Are you using Config UI X? v4.17.1 is the version I'm using where these logs are visible.

**Comment by merdok** [comment]
Ok, i just updated to the latest versions and also got the warning. Will check it out.

**Comment by merdok** [comment]
Fixed with my latest commit. 
@agneevX can you please check if that also fixes your other issue? You would need to manually replace the index.js. I want to make sure if this is just a cosmetic warning or really can cause other issues before i release a new version.

**Comment by coalfield** [comment]
> Fixed with my latest commit.
> 
confirmed latest commit on index.js has fixed it for me

**Comment by agneevX** [comment]
> You would need to manually replace the index.js.

Where is this located again?

**Comment by agneevX** [comment]
This issue is not resolved as the warnings are still shown https://github.com/merdok/homebridge-webos-tv/issues/226#issuecomment-625155990.

**Comment by merdok** [comment]
I did not yet release a new version with that fix since for now it just looks like a harmless warning. 

If you think that this could fix your issue then you need to manually replace the index.js and let me know, then i will release a new update with the fix included.

**Comment by Salvora** [comment]
Same warning comes up with me.

Homebridge Version: 1.1.0
Node.js Version | v14.2.0
Npm Version | v6.14.4
homebridge-webos-tv v1.7.1
